version: "3"
services:
  soccer-sim-web:
    image: wjrm500/soccer-simulation:latest
    command: python app.py
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - soccer-sim-redis

  soccer-sim-worker:
    image: wjrm500/soccer-simulation:latest
    command: python worker.py
    env_file:
      - .env
    depends_on:
      - soccer-sim-redis

  soccer-sim-cron:
    image: wjrm500/soccer-simulation:latest
    command: /bin/sh -c "while :; do sleep 43200; python delete_12_hour_mongodb_data.py; done"
    env_file:
      - .env
    depends_on:
      - soccer-sim-redis

  soccer-sim-redis:
    image: "redis:alpine"