version: "3"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 1G

  worker:
    build: .
    command: python worker.py
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 1G

  cron:
    build: .
    command: /bin/sh -c "while :; do sleep 43200; python delete_12_hour_mongodb_data.py; done"
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          memory: 512M

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
      - ./atlas_backup:/docker-entrypoint-initdb.d/atlas_backup:ro
      - ./init-mongorestore.sh:/docker-entrypoint-initdb.d/init-mongorestore.sh:ro
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  mongodb_data:
