version: "3"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 1G

  worker:
    build: .
    command: python worker.py
    env_file:
      - .env
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 1G

  cron:
    build: .
    command: /bin/sh -c "while :; do sleep 43200; python delete_12_hour_mongodb_data.py; done"
    env_file:
      - .env
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: "redis:alpine"
    deploy:
      resources:
        limits:
          memory: 512M