version: "3"
services:
  web:
    image: wjrm500/soccer-sim:latest
    command: python app.py
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    image: wjrm500/soccer-sim:latest
    command: python worker.py
    env_file:
      - .env
    depends_on:
      - redis

  cron:
    image: wjrm500/soccer-sim:latest
    command: /bin/sh -c "while :; do sleep 43200; python delete_12_hour_mongodb_data.py; done"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"