version: "3"
services:
  web:
    build: .
    command: uv run debugpy --listen 0.0.0.0:5678 -m gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5001:5000"
      - "5678:5678"
    volumes:
      - ./frontend:/app/frontend
      - ./ss:/app/ss
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 1G

  worker:
    build: .
    command: uv run debugpy --listen 0.0.0.0:5679 worker.py
    ports:
      - "5679:5679"
    volumes:
      - ./frontend:/app/frontend
      - ./ss:/app/ss
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 1G
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cron:
    build: .
    command: /bin/sh -c "while :; do sleep 43200; python delete_12_hour_mongodb_data.py; done"
    volumes:
      - ./frontend:/app/frontend
      - ./ss:/app/ss
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 256M
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          memory: 512M

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
      - ./static_data:/docker-entrypoint-initdb.d/static_data:ro
      - ./init-mongorestore.sh:/docker-entrypoint-initdb.d/init-mongorestore.sh:ro
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  mongodb_data:
