import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class EmailService:
    def __init__(self):
        self.sender_email = 'therealsoccersim@gmail.com'
        
    def send_email(self, recipient, subject, html_content):
        """
        Generic method to send any email
        """
        msg = MIMEMultipart('alternative')
        msg['From'] = self.sender_email
        msg['To'] = recipient
        msg['Subject'] = subject
        msg.attach(MIMEText(html_content, 'html'))
        
        try:
            with smtplib.SMTP('localhost') as server:
                server.send_message(msg)
                print(f"Email sent successfully to {recipient}")
        except Exception as e:
            print(f"Failed to send email: {str(e)}")

    def send_simulation_complete_email(self, recipient, universe_key):
        """
        Specific method for simulation completion emails
        """
        subject = 'Your Soccer Simulation is complete!'
        html_content = (
            f'<p>Dear {recipient},</p>'
            f'<p>Your Soccer Simulation (universe key <b>{universe_key}</b>) is complete!</p>'
            f'<p>Check it out <a href="wjrm500.com/soccer-simulation/simulation/{universe_key}">here</a>.</p>'
            '<p style="font-size: 0.9em;"><i>Email automatically generated by <b>Soccer Sim</b></i></p>'
        )
        self.send_email(recipient, subject, html_content)

    def send_mongodb_deletion_notification(self, deleted_files_count, deleted_chunks_count, total_bytes):
        """
        Specific method for MongoDB deletion notifications
        """
        subject = f'Soccer Simulation MongoDB notice - {deleted_files_count} files deleted'
        html_content = (
            f'{deleted_files_count} files and {deleted_chunks_count} chunks were just '
            f'removed from your MongoDB instance (a total of {total_bytes} bytes).'
        )
        self.send_email('wjrm500@gmail.com', subject, html_content)