import os

import brevo_python
from brevo_python.rest import ApiException
from dotenv import load_dotenv


class EmailService:
    def __init__(self):
        load_dotenv()
        self.sender_email = os.environ.get("SENDER_EMAIL")
        self.simulation_url = os.environ.get("SIMULATION_URL")
        self.api_key = os.environ.get("BREVO_API_KEY")
        self.enabled = all([self.sender_email, self.simulation_url, self.api_key])
        self.api_instance = None
        if not self.enabled:
            print(
                "Email service disabled. Check SENDER_EMAIL, SIMULATION_URL, and BREVO_API_KEY environment variables."
            )
        else:
            try:
                configuration = brevo_python.Configuration()
                configuration.api_key["api-key"] = self.api_key
                api_client = brevo_python.ApiClient(configuration)
                self.api_instance = brevo_python.TransactionalEmailsApi(api_client)
                print("Brevo Email Service Initialized.")
            except Exception as e:
                print(f"Error configuring Brevo client: {e}. Email service disabled.")
                self.enabled = False

    def send_email(self, recipient, subject, html_content):
        """
        Generic method to send any email using Brevo if enabled.
        """
        if not self.enabled or not self.api_instance:
            print("Skipping email send: Brevo service is disabled or configuration failed.")
            return

        send_smtp_email = brevo_python.SendSmtpEmail(
            sender={"email": self.sender_email},
            to=[{"email": recipient}],
            subject=subject,
            html_content=html_content,
        )

        try:
            api_response = self.api_instance.send_transac_email(send_smtp_email)
            print(f"Email sent successfully via Brevo. Message ID: {api_response.message_id}")
        except ApiException as e:
            print(f"Error sending email via Brevo: {e}")

    def send_simulation_complete_email(self, recipient, universe_key):
        """
        Specific method for simulation completion emails.
        """
        subject = "Your Soccer Simulation is complete!"
        html_content = (
            f"<p>Dear {recipient},</p>"
            f"<p>Your Soccer Simulation (universe key <b>{universe_key}</b>) is complete!</p>"
            f'<p>Check it out <a href="{self.simulation_url}/{universe_key}">here</a>.</p>'
            '<p style="font-size: 0.9em;">'
            "<i>Email automatically generated by <b>Soccer Sim</b></i>"
            "</p>"
        )
        self.send_email(recipient, subject, html_content)

    def send_mongodb_deletion_notification(
        self, deleted_files_count, deleted_chunks_count, total_bytes
    ):
        """
        Specific method for MongoDB deletion notifications.
        """
        subject = f"Soccer Simulation MongoDB notice - {deleted_files_count} files deleted"
        html_content = (
            f"{deleted_files_count} files and {deleted_chunks_count} chunks were just "
            f"removed from your MongoDB instance (a total of {total_bytes} bytes)."
        )
        self.send_email("wjrm500@gmail.com", subject, html_content)
