import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, To, Email, Content

def send_email(recipient_address, universe_key):
    from_email = Email('therealsoccersim@gmail.com')
    to_email = To(recipient_address)
    subject = 'Your Soccer Simulation is complete!'.format(universe_key)
    content = Content(
        'text/html',
        '<p>Dear {},</p>'.format(recipient_address) +
        '<p>Your Soccer Simulation (universe key <b>{}</b>) is complete!</p>'.format(universe_key) +
        '<p>Check it out <a href="soccer-sim.herokuapp.com/simulation/{}">here</a>.</p>'.format(universe_key) + 
        '<p style="font-size: 0.9em;"><i>Email automatically generated by <b>Soccer Sim</b></i></p>'
    )
    message = Mail(from_email, to_email, subject, content)
    try:
        sg = SendGridAPIClient(api_key = os.environ.get('SENDGRID_API_KEY'))
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(e.message)
