name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: "astral-sh/setup-uv@v5"

      - name: Set up Python using uv
        run: "uv python install"

      - name: Install project dependencies
        run: "uv sync --all-extras --dev"

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run Pytest
        run: "uv run pytest"
